# Generated by Django 5.1 on 2024-08-30 09:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogDetail',
            fields=[
                ('bid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('by', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('slug', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('data', models.TextField()),
                ('views', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ip_addr', models.GenericIPAddressField(unique=True, unpack_ipv4=True)),
                ('comment_data', models.TextField()),
                ('comment_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cynestia_site.blogdetail')),
            ],
        ),
    ]
